name = "MPIExecutor"
uuid = "a0f87982-966b-11e9-3bfe-57ffce2edb6d"
authors = ["Balazs Nemeth <balazs.nemeth@uhasselt.be>"]
version = "0.1.0"

[deps]
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
